// Copyright 2026 Project Arkilian Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/arkilian.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest represents a batch ingest request.
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// partition_key is the key used to route data to the appropriate partition.
	// Format depends on strategy: YYYYMMDD for time-based, tenant ID for tenant-based.
	PartitionKey string `protobuf:"bytes,1,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	// rows contains the batch of event rows to ingest.
	Rows []*Row `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	// idempotency_key is an optional key for idempotent ingestion.
	// If provided, duplicate requests with the same key will return the original result.
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_api_proto_arkilian_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arkilian_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_arkilian_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *IngestRequest) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *IngestRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// IngestResponse represents the response from a batch ingest operation.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// partition_id is the unique identifier of the created partition.
	PartitionId string `protobuf:"bytes,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	// row_count is the number of rows successfully ingested.
	RowCount int64 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// size_bytes is the size of the created partition in bytes.
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// request_id is the unique identifier for this request (for tracing).
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_api_proto_arkilian_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arkilian_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_arkilian_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

func (x *IngestResponse) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *IngestResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *IngestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Row represents a single event row to be ingested.
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is the optional ULID for the event.
	// If not provided, a new ULID will be generated.
	EventId []byte `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// tenant_id identifies the tenant this event belongs to (required).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// user_id identifies the user who triggered the event (required).
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// event_time is the Unix timestamp in nanoseconds when the event occurred (required).
	EventTime int64 `protobuf:"varint,4,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	// event_type categorizes the event, e.g., "page_view", "purchase" (required).
	EventType string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// payload contains the event-specific data as JSON bytes.
	// The payload will be compressed with Snappy before storage.
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_api_proto_arkilian_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_arkilian_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_api_proto_arkilian_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *Row) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Row) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Row) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Row) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Row) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_proto_arkilian_proto protoreflect.FileDescriptor

const file_api_proto_arkilian_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/arkilian.proto\x12\varkilian.v1\"\x83\x01\n" +
	"\rIngestRequest\x12#\n" +
	"\rpartition_key\x18\x01 \x01(\tR\fpartitionKey\x12$\n" +
	"\x04rows\x18\x02 \x03(\v2\x10.arkilian.v1.RowR\x04rows\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x8e\x01\n" +
	"\x0eIngestResponse\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\tR\vpartitionId\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x03R\browCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xae\x01\n" +
	"\x03Row\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"event_time\x18\x04 \x01(\x03R\teventTime\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload2W\n" +
	"\rIngestService\x12F\n" +
	"\vBatchIngest\x12\x1a.arkilian.v1.IngestRequest\x1a\x1b.arkilian.v1.IngestResponseB.Z,github.com/arkilian/arkilian/api/proto;protob\x06proto3"

var (
	file_api_proto_arkilian_proto_rawDescOnce sync.Once
	file_api_proto_arkilian_proto_rawDescData []byte
)

func file_api_proto_arkilian_proto_rawDescGZIP() []byte {
	file_api_proto_arkilian_proto_rawDescOnce.Do(func() {
		file_api_proto_arkilian_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_arkilian_proto_rawDesc), len(file_api_proto_arkilian_proto_rawDesc)))
	})
	return file_api_proto_arkilian_proto_rawDescData
}

var file_api_proto_arkilian_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_arkilian_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: arkilian.v1.IngestRequest
	(*IngestResponse)(nil), // 1: arkilian.v1.IngestResponse
	(*Row)(nil),            // 2: arkilian.v1.Row
}
var file_api_proto_arkilian_proto_depIdxs = []int32{
	2, // 0: arkilian.v1.IngestRequest.rows:type_name -> arkilian.v1.Row
	0, // 1: arkilian.v1.IngestService.BatchIngest:input_type -> arkilian.v1.IngestRequest
	1, // 2: arkilian.v1.IngestService.BatchIngest:output_type -> arkilian.v1.IngestResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_arkilian_proto_init() }
func file_api_proto_arkilian_proto_init() {
	if File_api_proto_arkilian_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_arkilian_proto_rawDesc), len(file_api_proto_arkilian_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_arkilian_proto_goTypes,
		DependencyIndexes: file_api_proto_arkilian_proto_depIdxs,
		MessageInfos:      file_api_proto_arkilian_proto_msgTypes,
	}.Build()
	File_api_proto_arkilian_proto = out.File
	file_api_proto_arkilian_proto_goTypes = nil
	file_api_proto_arkilian_proto_depIdxs = nil
}
