/* automatically generated by rust-bindgen 0.69.5 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct arkilian {
    _unused: [u8; 0],
}
extern "C" {
    pub fn db_init(
        db: *mut *mut arkilian,
        connection_url: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_close(db: *mut arkilian);
}
extern "C" {
    pub fn db_errmsg(db: *mut arkilian) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn db_set_token(
        db: *mut arkilian,
        token: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_exec(db: *mut arkilian, sql: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_prepare(
        db: *mut arkilian,
        sql: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_use_stmt(
        db: *mut arkilian,
        index: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_stmt_count(db: *mut arkilian) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_step(db: *mut arkilian) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_finalize(db: *mut arkilian) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_reset(db: *mut arkilian) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_column_count(db: *mut arkilian) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_column_name(
        db: *mut arkilian,
        col: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn db_column_text(
        db: *mut arkilian,
        col: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn db_column_int(db: *mut arkilian, col: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_column_double(db: *mut arkilian, col: ::std::os::raw::c_int) -> f64;
}
extern "C" {
    pub fn db_bind_text(
        db: *mut arkilian,
        idx: ::std::os::raw::c_int,
        val: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_bind_int(
        db: *mut arkilian,
        idx: ::std::os::raw::c_int,
        val: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn db_bind_double(
        db: *mut arkilian,
        idx: ::std::os::raw::c_int,
        val: f64,
    ) -> ::std::os::raw::c_int;
}
